Wallpapers = "~/Pictures/Wallpapers"
ghostty = "~/.config/ghostty"
nvim = "~/.config/nvim"
skhd = "~/.config/skhd"
"starship.toml" = "~/.config/starship.toml"
tmux = "~/.config/tmux"
yabai = "~/.config/yabai"
